// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: web_page.proto

package v0

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReadWebPageRequest_Fields int32

const (
	ReadWebPageRequest_URL          ReadWebPageRequest_Fields = 0
	ReadWebPageRequest_TEXT         ReadWebPageRequest_Fields = 1
	ReadWebPageRequest_WEB_SITE_KEY ReadWebPageRequest_Fields = 2
)

// Enum value maps for ReadWebPageRequest_Fields.
var (
	ReadWebPageRequest_Fields_name = map[int32]string{
		0: "URL",
		1: "TEXT",
		2: "WEB_SITE_KEY",
	}
	ReadWebPageRequest_Fields_value = map[string]int32{
		"URL":          0,
		"TEXT":         1,
		"WEB_SITE_KEY": 2,
	}
)

func (x ReadWebPageRequest_Fields) Enum() *ReadWebPageRequest_Fields {
	p := new(ReadWebPageRequest_Fields)
	*p = x
	return p
}

func (x ReadWebPageRequest_Fields) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadWebPageRequest_Fields) Descriptor() protoreflect.EnumDescriptor {
	return file_web_page_proto_enumTypes[0].Descriptor()
}

func (ReadWebPageRequest_Fields) Type() protoreflect.EnumType {
	return &file_web_page_proto_enumTypes[0]
}

func (x ReadWebPageRequest_Fields) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadWebPageRequest_Fields.Descriptor instead.
func (ReadWebPageRequest_Fields) EnumDescriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{3, 0}
}

type WebPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	WebSiteKey string `protobuf:"bytes,3,opt,name=web_site_key,json=webSiteKey,proto3" json:"web_site_key,omitempty"`
}

func (x *WebPage) Reset() {
	*x = WebPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPage) ProtoMessage() {}

func (x *WebPage) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPage.ProtoReflect.Descriptor instead.
func (*WebPage) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{0}
}

func (x *WebPage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebPage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *WebPage) GetWebSiteKey() string {
	if x != nil {
		return x.WebSiteKey
	}
	return ""
}

type CreateWebPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WebPages []*WebPage `protobuf:"bytes,1,rep,name=web_pages,json=webPages,proto3" json:"web_pages,omitempty"`
}

func (x *CreateWebPageRequest) Reset() {
	*x = CreateWebPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWebPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebPageRequest) ProtoMessage() {}

func (x *CreateWebPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebPageRequest.ProtoReflect.Descriptor instead.
func (*CreateWebPageRequest) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWebPageRequest) GetWebPages() []*WebPage {
	if x != nil {
		return x.WebPages
	}
	return nil
}

type CreateWebPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*CreateWebPageResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CreateWebPageResponse) Reset() {
	*x = CreateWebPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWebPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebPageResponse) ProtoMessage() {}

func (x *CreateWebPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebPageResponse.ProtoReflect.Descriptor instead.
func (*CreateWebPageResponse) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWebPageResponse) GetResults() []*CreateWebPageResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadWebPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys   []string                    `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Fields []ReadWebPageRequest_Fields `protobuf:"varint,2,rep,packed,name=fields,proto3,enum=v0.ReadWebPageRequest_Fields" json:"fields,omitempty"`
}

func (x *ReadWebPageRequest) Reset() {
	*x = ReadWebPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWebPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWebPageRequest) ProtoMessage() {}

func (x *ReadWebPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWebPageRequest.ProtoReflect.Descriptor instead.
func (*ReadWebPageRequest) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{3}
}

func (x *ReadWebPageRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ReadWebPageRequest) GetFields() []ReadWebPageRequest_Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ReadWebPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ReadWebPageResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ReadWebPageResponse) Reset() {
	*x = ReadWebPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWebPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWebPageResponse) ProtoMessage() {}

func (x *ReadWebPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWebPageResponse.ProtoReflect.Descriptor instead.
func (*ReadWebPageResponse) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{4}
}

func (x *ReadWebPageResponse) GetResults() []*ReadWebPageResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type UpdateWebPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*UpdateWebPageRequest_Updates `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *UpdateWebPageRequest) Reset() {
	*x = UpdateWebPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWebPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebPageRequest) ProtoMessage() {}

func (x *UpdateWebPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebPageRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebPageRequest) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWebPageRequest) GetUpdates() []*UpdateWebPageRequest_Updates {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateWebPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*UpdateWebPageResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *UpdateWebPageResponse) Reset() {
	*x = UpdateWebPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWebPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebPageResponse) ProtoMessage() {}

func (x *UpdateWebPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebPageResponse.ProtoReflect.Descriptor instead.
func (*UpdateWebPageResponse) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWebPageResponse) GetResults() []*UpdateWebPageResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteWebPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *DeleteWebPageRequest) Reset() {
	*x = DeleteWebPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWebPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebPageRequest) ProtoMessage() {}

func (x *DeleteWebPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebPageRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebPageRequest) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWebPageRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteWebPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DeleteWebPageResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *DeleteWebPageResponse) Reset() {
	*x = DeleteWebPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWebPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebPageResponse) ProtoMessage() {}

func (x *DeleteWebPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebPageResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebPageResponse) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWebPageResponse) GetResults() []*DeleteWebPageResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListWebPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumResults int32 `protobuf:"varint,1,opt,name=num_results,json=numResults,proto3" json:"num_results,omitempty"`
	Offset     int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListWebPageRequest) Reset() {
	*x = ListWebPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWebPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebPageRequest) ProtoMessage() {}

func (x *ListWebPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebPageRequest.ProtoReflect.Descriptor instead.
func (*ListWebPageRequest) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{9}
}

func (x *ListWebPageRequest) GetNumResults() int32 {
	if x != nil {
		return x.NumResults
	}
	return 0
}

func (x *ListWebPageRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWebPageResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ListWebPageResults) Reset() {
	*x = ListWebPageResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWebPageResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebPageResults) ProtoMessage() {}

func (x *ListWebPageResults) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebPageResults.ProtoReflect.Descriptor instead.
func (*ListWebPageResults) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{10}
}

func (x *ListWebPageResults) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CreateWebPageResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateWebPageResponse_Result) Reset() {
	*x = CreateWebPageResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWebPageResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebPageResponse_Result) ProtoMessage() {}

func (x *CreateWebPageResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebPageResponse_Result.ProtoReflect.Descriptor instead.
func (*CreateWebPageResponse_Result) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateWebPageResponse_Result) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateWebPageResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadWebPageResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	WebPage *WebPage            `protobuf:"bytes,2,opt,name=web_page,json=webPage,proto3" json:"web_page,omitempty"`
	Sources []*SourceAccounting `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Error   string              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReadWebPageResponse_Result) Reset() {
	*x = ReadWebPageResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWebPageResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWebPageResponse_Result) ProtoMessage() {}

func (x *ReadWebPageResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWebPageResponse_Result.ProtoReflect.Descriptor instead.
func (*ReadWebPageResponse_Result) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ReadWebPageResponse_Result) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadWebPageResponse_Result) GetWebPage() *WebPage {
	if x != nil {
		return x.WebPage
	}
	return nil
}

func (x *ReadWebPageResponse_Result) GetSources() []*SourceAccounting {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ReadWebPageResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateWebPageRequest_Updates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	WebPage *WebPage `protobuf:"bytes,2,opt,name=web_page,json=webPage,proto3" json:"web_page,omitempty"`
}

func (x *UpdateWebPageRequest_Updates) Reset() {
	*x = UpdateWebPageRequest_Updates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWebPageRequest_Updates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebPageRequest_Updates) ProtoMessage() {}

func (x *UpdateWebPageRequest_Updates) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebPageRequest_Updates.ProtoReflect.Descriptor instead.
func (*UpdateWebPageRequest_Updates) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpdateWebPageRequest_Updates) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateWebPageRequest_Updates) GetWebPage() *WebPage {
	if x != nil {
		return x.WebPage
	}
	return nil
}

type UpdateWebPageResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateWebPageResponse_Result) Reset() {
	*x = UpdateWebPageResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWebPageResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebPageResponse_Result) ProtoMessage() {}

func (x *UpdateWebPageResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebPageResponse_Result.ProtoReflect.Descriptor instead.
func (*UpdateWebPageResponse_Result) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpdateWebPageResponse_Result) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateWebPageResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteWebPageResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteWebPageResponse_Result) Reset() {
	*x = DeleteWebPageResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_page_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWebPageResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebPageResponse_Result) ProtoMessage() {}

func (x *DeleteWebPageResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_web_page_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebPageResponse_Result.ProtoReflect.Descriptor instead.
func (*DeleteWebPageResponse_Result) Descriptor() ([]byte, []int) {
	return file_web_page_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DeleteWebPageResponse_Result) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteWebPageResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_web_page_proto protoreflect.FileDescriptor

var file_web_page_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x65, 0x62, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x76, 0x30, 0x1a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x07, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x77, 0x65, 0x62, 0x5f, 0x73,
	0x69, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77,
	0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x40, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x09, 0x77, 0x65, 0x62, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x30, 0x2e, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x08, 0x77, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x15,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x1a, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x8e, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x35,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x76, 0x30, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x2d, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x07, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x45, 0x42, 0x5f, 0x53, 0x49, 0x54, 0x45, 0x5f, 0x4b,
	0x45, 0x59, 0x10, 0x02, 0x22, 0xda, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x76, 0x30, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x88, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x08, 0x77, 0x65, 0x62, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x30, 0x2e, 0x57, 0x65, 0x62, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x77, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76,
	0x30, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x97, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x30,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x43, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x08, 0x77, 0x65, 0x62, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x30, 0x2e, 0x57, 0x65, 0x62, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x77, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x30, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x1a, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x62,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22,
	0x85, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x30, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65,
	0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x32, 0xec, 0x02, 0x0a, 0x0e, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x76, 0x30, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x52,
	0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x76, 0x30, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x76, 0x30, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x2e, 0x76, 0x30, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x30, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57,
	0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x76, 0x30, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x76, 0x30, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x62, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e,
	0x76, 0x30, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x30, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x3b, 0x76, 0x30,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web_page_proto_rawDescOnce sync.Once
	file_web_page_proto_rawDescData = file_web_page_proto_rawDesc
)

func file_web_page_proto_rawDescGZIP() []byte {
	file_web_page_proto_rawDescOnce.Do(func() {
		file_web_page_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_page_proto_rawDescData)
	})
	return file_web_page_proto_rawDescData
}

var file_web_page_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_web_page_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_web_page_proto_goTypes = []interface{}{
	(ReadWebPageRequest_Fields)(0),       // 0: v0.ReadWebPageRequest.Fields
	(*WebPage)(nil),                      // 1: v0.WebPage
	(*CreateWebPageRequest)(nil),         // 2: v0.CreateWebPageRequest
	(*CreateWebPageResponse)(nil),        // 3: v0.CreateWebPageResponse
	(*ReadWebPageRequest)(nil),           // 4: v0.ReadWebPageRequest
	(*ReadWebPageResponse)(nil),          // 5: v0.ReadWebPageResponse
	(*UpdateWebPageRequest)(nil),         // 6: v0.UpdateWebPageRequest
	(*UpdateWebPageResponse)(nil),        // 7: v0.UpdateWebPageResponse
	(*DeleteWebPageRequest)(nil),         // 8: v0.DeleteWebPageRequest
	(*DeleteWebPageResponse)(nil),        // 9: v0.DeleteWebPageResponse
	(*ListWebPageRequest)(nil),           // 10: v0.ListWebPageRequest
	(*ListWebPageResults)(nil),           // 11: v0.ListWebPageResults
	(*CreateWebPageResponse_Result)(nil), // 12: v0.CreateWebPageResponse.Result
	(*ReadWebPageResponse_Result)(nil),   // 13: v0.ReadWebPageResponse.Result
	(*UpdateWebPageRequest_Updates)(nil), // 14: v0.UpdateWebPageRequest.Updates
	(*UpdateWebPageResponse_Result)(nil), // 15: v0.UpdateWebPageResponse.Result
	(*DeleteWebPageResponse_Result)(nil), // 16: v0.DeleteWebPageResponse.Result
	(*SourceAccounting)(nil),             // 17: v0.SourceAccounting
}
var file_web_page_proto_depIdxs = []int32{
	1,  // 0: v0.CreateWebPageRequest.web_pages:type_name -> v0.WebPage
	12, // 1: v0.CreateWebPageResponse.results:type_name -> v0.CreateWebPageResponse.Result
	0,  // 2: v0.ReadWebPageRequest.fields:type_name -> v0.ReadWebPageRequest.Fields
	13, // 3: v0.ReadWebPageResponse.results:type_name -> v0.ReadWebPageResponse.Result
	14, // 4: v0.UpdateWebPageRequest.updates:type_name -> v0.UpdateWebPageRequest.Updates
	15, // 5: v0.UpdateWebPageResponse.results:type_name -> v0.UpdateWebPageResponse.Result
	16, // 6: v0.DeleteWebPageResponse.results:type_name -> v0.DeleteWebPageResponse.Result
	1,  // 7: v0.ReadWebPageResponse.Result.web_page:type_name -> v0.WebPage
	17, // 8: v0.ReadWebPageResponse.Result.sources:type_name -> v0.SourceAccounting
	1,  // 9: v0.UpdateWebPageRequest.Updates.web_page:type_name -> v0.WebPage
	2,  // 10: v0.WebPageService.CreateWebPage:input_type -> v0.CreateWebPageRequest
	4,  // 11: v0.WebPageService.ReadWebPage:input_type -> v0.ReadWebPageRequest
	6,  // 12: v0.WebPageService.UpdateWebPage:input_type -> v0.UpdateWebPageRequest
	8,  // 13: v0.WebPageService.DeleteWebPage:input_type -> v0.DeleteWebPageRequest
	10, // 14: v0.WebPageService.ListWebPages:input_type -> v0.ListWebPageRequest
	3,  // 15: v0.WebPageService.CreateWebPage:output_type -> v0.CreateWebPageResponse
	5,  // 16: v0.WebPageService.ReadWebPage:output_type -> v0.ReadWebPageResponse
	7,  // 17: v0.WebPageService.UpdateWebPage:output_type -> v0.UpdateWebPageResponse
	9,  // 18: v0.WebPageService.DeleteWebPage:output_type -> v0.DeleteWebPageResponse
	11, // 19: v0.WebPageService.ListWebPages:output_type -> v0.ListWebPageResults
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_web_page_proto_init() }
func file_web_page_proto_init() {
	if File_web_page_proto != nil {
		return
	}
	file_accounting_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_web_page_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWebPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWebPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWebPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWebPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWebPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWebPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWebPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWebPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWebPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWebPageResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWebPageResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWebPageResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWebPageRequest_Updates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWebPageResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_page_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWebPageResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_page_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_page_proto_goTypes,
		DependencyIndexes: file_web_page_proto_depIdxs,
		EnumInfos:         file_web_page_proto_enumTypes,
		MessageInfos:      file_web_page_proto_msgTypes,
	}.Build()
	File_web_page_proto = out.File
	file_web_page_proto_rawDesc = nil
	file_web_page_proto_goTypes = nil
	file_web_page_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WebPageServiceClient is the client API for WebPageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebPageServiceClient interface {
	CreateWebPage(ctx context.Context, in *CreateWebPageRequest, opts ...grpc.CallOption) (*CreateWebPageResponse, error)
	ReadWebPage(ctx context.Context, in *ReadWebPageRequest, opts ...grpc.CallOption) (*ReadWebPageResponse, error)
	UpdateWebPage(ctx context.Context, in *UpdateWebPageRequest, opts ...grpc.CallOption) (*UpdateWebPageResponse, error)
	DeleteWebPage(ctx context.Context, in *DeleteWebPageRequest, opts ...grpc.CallOption) (*DeleteWebPageResponse, error)
	ListWebPages(ctx context.Context, in *ListWebPageRequest, opts ...grpc.CallOption) (*ListWebPageResults, error)
}

type webPageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebPageServiceClient(cc grpc.ClientConnInterface) WebPageServiceClient {
	return &webPageServiceClient{cc}
}

func (c *webPageServiceClient) CreateWebPage(ctx context.Context, in *CreateWebPageRequest, opts ...grpc.CallOption) (*CreateWebPageResponse, error) {
	out := new(CreateWebPageResponse)
	err := c.cc.Invoke(ctx, "/v0.WebPageService/CreateWebPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webPageServiceClient) ReadWebPage(ctx context.Context, in *ReadWebPageRequest, opts ...grpc.CallOption) (*ReadWebPageResponse, error) {
	out := new(ReadWebPageResponse)
	err := c.cc.Invoke(ctx, "/v0.WebPageService/ReadWebPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webPageServiceClient) UpdateWebPage(ctx context.Context, in *UpdateWebPageRequest, opts ...grpc.CallOption) (*UpdateWebPageResponse, error) {
	out := new(UpdateWebPageResponse)
	err := c.cc.Invoke(ctx, "/v0.WebPageService/UpdateWebPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webPageServiceClient) DeleteWebPage(ctx context.Context, in *DeleteWebPageRequest, opts ...grpc.CallOption) (*DeleteWebPageResponse, error) {
	out := new(DeleteWebPageResponse)
	err := c.cc.Invoke(ctx, "/v0.WebPageService/DeleteWebPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webPageServiceClient) ListWebPages(ctx context.Context, in *ListWebPageRequest, opts ...grpc.CallOption) (*ListWebPageResults, error) {
	out := new(ListWebPageResults)
	err := c.cc.Invoke(ctx, "/v0.WebPageService/ListWebPages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebPageServiceServer is the server API for WebPageService service.
type WebPageServiceServer interface {
	CreateWebPage(context.Context, *CreateWebPageRequest) (*CreateWebPageResponse, error)
	ReadWebPage(context.Context, *ReadWebPageRequest) (*ReadWebPageResponse, error)
	UpdateWebPage(context.Context, *UpdateWebPageRequest) (*UpdateWebPageResponse, error)
	DeleteWebPage(context.Context, *DeleteWebPageRequest) (*DeleteWebPageResponse, error)
	ListWebPages(context.Context, *ListWebPageRequest) (*ListWebPageResults, error)
}

// UnimplementedWebPageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWebPageServiceServer struct {
}

func (*UnimplementedWebPageServiceServer) CreateWebPage(context.Context, *CreateWebPageRequest) (*CreateWebPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWebPage not implemented")
}
func (*UnimplementedWebPageServiceServer) ReadWebPage(context.Context, *ReadWebPageRequest) (*ReadWebPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadWebPage not implemented")
}
func (*UnimplementedWebPageServiceServer) UpdateWebPage(context.Context, *UpdateWebPageRequest) (*UpdateWebPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWebPage not implemented")
}
func (*UnimplementedWebPageServiceServer) DeleteWebPage(context.Context, *DeleteWebPageRequest) (*DeleteWebPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWebPage not implemented")
}
func (*UnimplementedWebPageServiceServer) ListWebPages(context.Context, *ListWebPageRequest) (*ListWebPageResults, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWebPages not implemented")
}

func RegisterWebPageServiceServer(s *grpc.Server, srv WebPageServiceServer) {
	s.RegisterService(&_WebPageService_serviceDesc, srv)
}

func _WebPageService_CreateWebPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebPageServiceServer).CreateWebPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebPageService/CreateWebPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebPageServiceServer).CreateWebPage(ctx, req.(*CreateWebPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebPageService_ReadWebPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadWebPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebPageServiceServer).ReadWebPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebPageService/ReadWebPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebPageServiceServer).ReadWebPage(ctx, req.(*ReadWebPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebPageService_UpdateWebPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWebPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebPageServiceServer).UpdateWebPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebPageService/UpdateWebPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebPageServiceServer).UpdateWebPage(ctx, req.(*UpdateWebPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebPageService_DeleteWebPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebPageServiceServer).DeleteWebPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebPageService/DeleteWebPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebPageServiceServer).DeleteWebPage(ctx, req.(*DeleteWebPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebPageService_ListWebPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebPageServiceServer).ListWebPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebPageService/ListWebPages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebPageServiceServer).ListWebPages(ctx, req.(*ListWebPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebPageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v0.WebPageService",
	HandlerType: (*WebPageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWebPage",
			Handler:    _WebPageService_CreateWebPage_Handler,
		},
		{
			MethodName: "ReadWebPage",
			Handler:    _WebPageService_ReadWebPage_Handler,
		},
		{
			MethodName: "UpdateWebPage",
			Handler:    _WebPageService_UpdateWebPage_Handler,
		},
		{
			MethodName: "DeleteWebPage",
			Handler:    _WebPageService_DeleteWebPage_Handler,
		},
		{
			MethodName: "ListWebPages",
			Handler:    _WebPageService_ListWebPages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web_page.proto",
}
