// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: web_site.proto

package v0

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReadWebSiteRequest_Fields int32

const (
	ReadWebSiteRequest_URL         ReadWebSiteRequest_Fields = 0
	ReadWebSiteRequest_IN_LANGUAGE ReadWebSiteRequest_Fields = 1
)

// Enum value maps for ReadWebSiteRequest_Fields.
var (
	ReadWebSiteRequest_Fields_name = map[int32]string{
		0: "URL",
		1: "IN_LANGUAGE",
	}
	ReadWebSiteRequest_Fields_value = map[string]int32{
		"URL":         0,
		"IN_LANGUAGE": 1,
	}
)

func (x ReadWebSiteRequest_Fields) Enum() *ReadWebSiteRequest_Fields {
	p := new(ReadWebSiteRequest_Fields)
	*p = x
	return p
}

func (x ReadWebSiteRequest_Fields) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadWebSiteRequest_Fields) Descriptor() protoreflect.EnumDescriptor {
	return file_web_site_proto_enumTypes[0].Descriptor()
}

func (ReadWebSiteRequest_Fields) Type() protoreflect.EnumType {
	return &file_web_site_proto_enumTypes[0]
}

func (x ReadWebSiteRequest_Fields) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadWebSiteRequest_Fields.Descriptor instead.
func (ReadWebSiteRequest_Fields) EnumDescriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{3, 0}
}

type WebSite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	InLanguage string `protobuf:"bytes,2,opt,name=in_language,json=inLanguage,proto3" json:"in_language,omitempty"`
}

func (x *WebSite) Reset() {
	*x = WebSite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSite) ProtoMessage() {}

func (x *WebSite) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSite.ProtoReflect.Descriptor instead.
func (*WebSite) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{0}
}

func (x *WebSite) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebSite) GetInLanguage() string {
	if x != nil {
		return x.InLanguage
	}
	return ""
}

type CreateWebSiteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WebSites []*WebSite `protobuf:"bytes,1,rep,name=web_sites,json=webSites,proto3" json:"web_sites,omitempty"`
}

func (x *CreateWebSiteRequest) Reset() {
	*x = CreateWebSiteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWebSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebSiteRequest) ProtoMessage() {}

func (x *CreateWebSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebSiteRequest.ProtoReflect.Descriptor instead.
func (*CreateWebSiteRequest) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWebSiteRequest) GetWebSites() []*WebSite {
	if x != nil {
		return x.WebSites
	}
	return nil
}

type CreateWebSiteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*CreateWebSiteResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CreateWebSiteResponse) Reset() {
	*x = CreateWebSiteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWebSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebSiteResponse) ProtoMessage() {}

func (x *CreateWebSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebSiteResponse.ProtoReflect.Descriptor instead.
func (*CreateWebSiteResponse) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWebSiteResponse) GetResults() []*CreateWebSiteResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadWebSiteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys   []string                    `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Fields []ReadWebSiteRequest_Fields `protobuf:"varint,2,rep,packed,name=fields,proto3,enum=v0.ReadWebSiteRequest_Fields" json:"fields,omitempty"`
}

func (x *ReadWebSiteRequest) Reset() {
	*x = ReadWebSiteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWebSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWebSiteRequest) ProtoMessage() {}

func (x *ReadWebSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWebSiteRequest.ProtoReflect.Descriptor instead.
func (*ReadWebSiteRequest) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{3}
}

func (x *ReadWebSiteRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ReadWebSiteRequest) GetFields() []ReadWebSiteRequest_Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ReadWebSiteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ReadWebSiteResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ReadWebSiteResponse) Reset() {
	*x = ReadWebSiteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWebSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWebSiteResponse) ProtoMessage() {}

func (x *ReadWebSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWebSiteResponse.ProtoReflect.Descriptor instead.
func (*ReadWebSiteResponse) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{4}
}

func (x *ReadWebSiteResponse) GetResults() []*ReadWebSiteResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type UpdateWebSiteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*UpdateWebSiteRequest_Updates `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *UpdateWebSiteRequest) Reset() {
	*x = UpdateWebSiteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWebSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebSiteRequest) ProtoMessage() {}

func (x *UpdateWebSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebSiteRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebSiteRequest) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWebSiteRequest) GetUpdates() []*UpdateWebSiteRequest_Updates {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateWebSiteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*UpdateWebSiteResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *UpdateWebSiteResponse) Reset() {
	*x = UpdateWebSiteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWebSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebSiteResponse) ProtoMessage() {}

func (x *UpdateWebSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebSiteResponse.ProtoReflect.Descriptor instead.
func (*UpdateWebSiteResponse) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWebSiteResponse) GetResults() []*UpdateWebSiteResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteWebSiteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *DeleteWebSiteRequest) Reset() {
	*x = DeleteWebSiteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWebSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebSiteRequest) ProtoMessage() {}

func (x *DeleteWebSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebSiteRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebSiteRequest) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWebSiteRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteWebSiteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DeleteWebSiteResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *DeleteWebSiteResponse) Reset() {
	*x = DeleteWebSiteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWebSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebSiteResponse) ProtoMessage() {}

func (x *DeleteWebSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebSiteResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebSiteResponse) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWebSiteResponse) GetResults() []*DeleteWebSiteResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListWebSiteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumResults int32 `protobuf:"varint,1,opt,name=num_results,json=numResults,proto3" json:"num_results,omitempty"`
	Offset     int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListWebSiteRequest) Reset() {
	*x = ListWebSiteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWebSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebSiteRequest) ProtoMessage() {}

func (x *ListWebSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebSiteRequest.ProtoReflect.Descriptor instead.
func (*ListWebSiteRequest) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{9}
}

func (x *ListWebSiteRequest) GetNumResults() int32 {
	if x != nil {
		return x.NumResults
	}
	return 0
}

func (x *ListWebSiteRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWebSiteResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ListWebSiteResults) Reset() {
	*x = ListWebSiteResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWebSiteResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebSiteResults) ProtoMessage() {}

func (x *ListWebSiteResults) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebSiteResults.ProtoReflect.Descriptor instead.
func (*ListWebSiteResults) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{10}
}

func (x *ListWebSiteResults) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CreateWebSiteResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateWebSiteResponse_Result) Reset() {
	*x = CreateWebSiteResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWebSiteResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebSiteResponse_Result) ProtoMessage() {}

func (x *CreateWebSiteResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebSiteResponse_Result.ProtoReflect.Descriptor instead.
func (*CreateWebSiteResponse_Result) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateWebSiteResponse_Result) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateWebSiteResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadWebSiteResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	WebSite *WebSite            `protobuf:"bytes,2,opt,name=web_site,json=webSite,proto3" json:"web_site,omitempty"`
	Sources []*SourceAccounting `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Error   string              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReadWebSiteResponse_Result) Reset() {
	*x = ReadWebSiteResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWebSiteResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWebSiteResponse_Result) ProtoMessage() {}

func (x *ReadWebSiteResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWebSiteResponse_Result.ProtoReflect.Descriptor instead.
func (*ReadWebSiteResponse_Result) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ReadWebSiteResponse_Result) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadWebSiteResponse_Result) GetWebSite() *WebSite {
	if x != nil {
		return x.WebSite
	}
	return nil
}

func (x *ReadWebSiteResponse_Result) GetSources() []*SourceAccounting {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ReadWebSiteResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateWebSiteRequest_Updates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	WebSite *WebSite `protobuf:"bytes,2,opt,name=web_site,json=webSite,proto3" json:"web_site,omitempty"`
}

func (x *UpdateWebSiteRequest_Updates) Reset() {
	*x = UpdateWebSiteRequest_Updates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWebSiteRequest_Updates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebSiteRequest_Updates) ProtoMessage() {}

func (x *UpdateWebSiteRequest_Updates) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebSiteRequest_Updates.ProtoReflect.Descriptor instead.
func (*UpdateWebSiteRequest_Updates) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpdateWebSiteRequest_Updates) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateWebSiteRequest_Updates) GetWebSite() *WebSite {
	if x != nil {
		return x.WebSite
	}
	return nil
}

type UpdateWebSiteResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateWebSiteResponse_Result) Reset() {
	*x = UpdateWebSiteResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWebSiteResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebSiteResponse_Result) ProtoMessage() {}

func (x *UpdateWebSiteResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebSiteResponse_Result.ProtoReflect.Descriptor instead.
func (*UpdateWebSiteResponse_Result) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpdateWebSiteResponse_Result) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateWebSiteResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteWebSiteResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteWebSiteResponse_Result) Reset() {
	*x = DeleteWebSiteResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_site_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWebSiteResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebSiteResponse_Result) ProtoMessage() {}

func (x *DeleteWebSiteResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_web_site_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebSiteResponse_Result.ProtoReflect.Descriptor instead.
func (*DeleteWebSiteResponse_Result) Descriptor() ([]byte, []int) {
	return file_web_site_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DeleteWebSiteResponse_Result) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteWebSiteResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_web_site_proto protoreflect.FileDescriptor

var file_web_site_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x65, 0x62, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x76, 0x30, 0x1a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x07, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65,
	0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x09,
	0x77, 0x65, 0x62, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x76, 0x30, 0x2e, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x08, 0x77, 0x65,
	0x62, 0x53, 0x69, 0x74, 0x65, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62,
	0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x30, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x83,
	0x01, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x76, 0x30, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x22, 0x22, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x52,
	0x4c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x4c, 0x41, 0x4e, 0x47, 0x55, 0x41,
	0x47, 0x45, 0x10, 0x01, 0x22, 0xda, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62,
	0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x76, 0x30, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x88, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x08, 0x77, 0x65, 0x62, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x30, 0x2e, 0x57, 0x65, 0x62, 0x53, 0x69,
	0x74, 0x65, 0x52, 0x07, 0x77, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76,
	0x30, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x97, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x30,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x43, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x08, 0x77, 0x65, 0x62, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x30, 0x2e, 0x57, 0x65, 0x62, 0x53, 0x69,
	0x74, 0x65, 0x52, 0x07, 0x77, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x30, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x1a, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x62,
	0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22,
	0x85, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x30, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65,
	0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x32, 0xec, 0x02, 0x0a, 0x0e, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62,
	0x53, 0x69, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x76, 0x30, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x52,
	0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x76, 0x30, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x76, 0x30, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x65, 0x62, 0x53,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x12, 0x18,
	0x2e, 0x76, 0x30, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x30, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57,
	0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x76, 0x30, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x76, 0x30, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x73, 0x12, 0x16, 0x2e,
	0x76, 0x30, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x30, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x3b, 0x76, 0x30,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web_site_proto_rawDescOnce sync.Once
	file_web_site_proto_rawDescData = file_web_site_proto_rawDesc
)

func file_web_site_proto_rawDescGZIP() []byte {
	file_web_site_proto_rawDescOnce.Do(func() {
		file_web_site_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_site_proto_rawDescData)
	})
	return file_web_site_proto_rawDescData
}

var file_web_site_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_web_site_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_web_site_proto_goTypes = []interface{}{
	(ReadWebSiteRequest_Fields)(0),       // 0: v0.ReadWebSiteRequest.Fields
	(*WebSite)(nil),                      // 1: v0.WebSite
	(*CreateWebSiteRequest)(nil),         // 2: v0.CreateWebSiteRequest
	(*CreateWebSiteResponse)(nil),        // 3: v0.CreateWebSiteResponse
	(*ReadWebSiteRequest)(nil),           // 4: v0.ReadWebSiteRequest
	(*ReadWebSiteResponse)(nil),          // 5: v0.ReadWebSiteResponse
	(*UpdateWebSiteRequest)(nil),         // 6: v0.UpdateWebSiteRequest
	(*UpdateWebSiteResponse)(nil),        // 7: v0.UpdateWebSiteResponse
	(*DeleteWebSiteRequest)(nil),         // 8: v0.DeleteWebSiteRequest
	(*DeleteWebSiteResponse)(nil),        // 9: v0.DeleteWebSiteResponse
	(*ListWebSiteRequest)(nil),           // 10: v0.ListWebSiteRequest
	(*ListWebSiteResults)(nil),           // 11: v0.ListWebSiteResults
	(*CreateWebSiteResponse_Result)(nil), // 12: v0.CreateWebSiteResponse.Result
	(*ReadWebSiteResponse_Result)(nil),   // 13: v0.ReadWebSiteResponse.Result
	(*UpdateWebSiteRequest_Updates)(nil), // 14: v0.UpdateWebSiteRequest.Updates
	(*UpdateWebSiteResponse_Result)(nil), // 15: v0.UpdateWebSiteResponse.Result
	(*DeleteWebSiteResponse_Result)(nil), // 16: v0.DeleteWebSiteResponse.Result
	(*SourceAccounting)(nil),             // 17: v0.SourceAccounting
}
var file_web_site_proto_depIdxs = []int32{
	1,  // 0: v0.CreateWebSiteRequest.web_sites:type_name -> v0.WebSite
	12, // 1: v0.CreateWebSiteResponse.results:type_name -> v0.CreateWebSiteResponse.Result
	0,  // 2: v0.ReadWebSiteRequest.fields:type_name -> v0.ReadWebSiteRequest.Fields
	13, // 3: v0.ReadWebSiteResponse.results:type_name -> v0.ReadWebSiteResponse.Result
	14, // 4: v0.UpdateWebSiteRequest.updates:type_name -> v0.UpdateWebSiteRequest.Updates
	15, // 5: v0.UpdateWebSiteResponse.results:type_name -> v0.UpdateWebSiteResponse.Result
	16, // 6: v0.DeleteWebSiteResponse.results:type_name -> v0.DeleteWebSiteResponse.Result
	1,  // 7: v0.ReadWebSiteResponse.Result.web_site:type_name -> v0.WebSite
	17, // 8: v0.ReadWebSiteResponse.Result.sources:type_name -> v0.SourceAccounting
	1,  // 9: v0.UpdateWebSiteRequest.Updates.web_site:type_name -> v0.WebSite
	2,  // 10: v0.WebSiteService.CreateWebSite:input_type -> v0.CreateWebSiteRequest
	4,  // 11: v0.WebSiteService.ReadWebSite:input_type -> v0.ReadWebSiteRequest
	6,  // 12: v0.WebSiteService.UpdateWebSite:input_type -> v0.UpdateWebSiteRequest
	8,  // 13: v0.WebSiteService.DeleteWebSite:input_type -> v0.DeleteWebSiteRequest
	10, // 14: v0.WebSiteService.ListWebSites:input_type -> v0.ListWebSiteRequest
	3,  // 15: v0.WebSiteService.CreateWebSite:output_type -> v0.CreateWebSiteResponse
	5,  // 16: v0.WebSiteService.ReadWebSite:output_type -> v0.ReadWebSiteResponse
	7,  // 17: v0.WebSiteService.UpdateWebSite:output_type -> v0.UpdateWebSiteResponse
	9,  // 18: v0.WebSiteService.DeleteWebSite:output_type -> v0.DeleteWebSiteResponse
	11, // 19: v0.WebSiteService.ListWebSites:output_type -> v0.ListWebSiteResults
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_web_site_proto_init() }
func file_web_site_proto_init() {
	if File_web_site_proto != nil {
		return
	}
	file_accounting_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_web_site_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebSite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWebSiteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWebSiteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWebSiteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWebSiteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWebSiteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWebSiteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWebSiteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWebSiteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWebSiteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWebSiteResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWebSiteResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWebSiteResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWebSiteRequest_Updates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWebSiteResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_site_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWebSiteResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_site_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_site_proto_goTypes,
		DependencyIndexes: file_web_site_proto_depIdxs,
		EnumInfos:         file_web_site_proto_enumTypes,
		MessageInfos:      file_web_site_proto_msgTypes,
	}.Build()
	File_web_site_proto = out.File
	file_web_site_proto_rawDesc = nil
	file_web_site_proto_goTypes = nil
	file_web_site_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WebSiteServiceClient is the client API for WebSiteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebSiteServiceClient interface {
	CreateWebSite(ctx context.Context, in *CreateWebSiteRequest, opts ...grpc.CallOption) (*CreateWebSiteResponse, error)
	ReadWebSite(ctx context.Context, in *ReadWebSiteRequest, opts ...grpc.CallOption) (*ReadWebSiteResponse, error)
	UpdateWebSite(ctx context.Context, in *UpdateWebSiteRequest, opts ...grpc.CallOption) (*UpdateWebSiteResponse, error)
	DeleteWebSite(ctx context.Context, in *DeleteWebSiteRequest, opts ...grpc.CallOption) (*DeleteWebSiteResponse, error)
	ListWebSites(ctx context.Context, in *ListWebSiteRequest, opts ...grpc.CallOption) (*ListWebSiteResults, error)
}

type webSiteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebSiteServiceClient(cc grpc.ClientConnInterface) WebSiteServiceClient {
	return &webSiteServiceClient{cc}
}

func (c *webSiteServiceClient) CreateWebSite(ctx context.Context, in *CreateWebSiteRequest, opts ...grpc.CallOption) (*CreateWebSiteResponse, error) {
	out := new(CreateWebSiteResponse)
	err := c.cc.Invoke(ctx, "/v0.WebSiteService/CreateWebSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webSiteServiceClient) ReadWebSite(ctx context.Context, in *ReadWebSiteRequest, opts ...grpc.CallOption) (*ReadWebSiteResponse, error) {
	out := new(ReadWebSiteResponse)
	err := c.cc.Invoke(ctx, "/v0.WebSiteService/ReadWebSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webSiteServiceClient) UpdateWebSite(ctx context.Context, in *UpdateWebSiteRequest, opts ...grpc.CallOption) (*UpdateWebSiteResponse, error) {
	out := new(UpdateWebSiteResponse)
	err := c.cc.Invoke(ctx, "/v0.WebSiteService/UpdateWebSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webSiteServiceClient) DeleteWebSite(ctx context.Context, in *DeleteWebSiteRequest, opts ...grpc.CallOption) (*DeleteWebSiteResponse, error) {
	out := new(DeleteWebSiteResponse)
	err := c.cc.Invoke(ctx, "/v0.WebSiteService/DeleteWebSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webSiteServiceClient) ListWebSites(ctx context.Context, in *ListWebSiteRequest, opts ...grpc.CallOption) (*ListWebSiteResults, error) {
	out := new(ListWebSiteResults)
	err := c.cc.Invoke(ctx, "/v0.WebSiteService/ListWebSites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebSiteServiceServer is the server API for WebSiteService service.
type WebSiteServiceServer interface {
	CreateWebSite(context.Context, *CreateWebSiteRequest) (*CreateWebSiteResponse, error)
	ReadWebSite(context.Context, *ReadWebSiteRequest) (*ReadWebSiteResponse, error)
	UpdateWebSite(context.Context, *UpdateWebSiteRequest) (*UpdateWebSiteResponse, error)
	DeleteWebSite(context.Context, *DeleteWebSiteRequest) (*DeleteWebSiteResponse, error)
	ListWebSites(context.Context, *ListWebSiteRequest) (*ListWebSiteResults, error)
}

// UnimplementedWebSiteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWebSiteServiceServer struct {
}

func (*UnimplementedWebSiteServiceServer) CreateWebSite(context.Context, *CreateWebSiteRequest) (*CreateWebSiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWebSite not implemented")
}
func (*UnimplementedWebSiteServiceServer) ReadWebSite(context.Context, *ReadWebSiteRequest) (*ReadWebSiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadWebSite not implemented")
}
func (*UnimplementedWebSiteServiceServer) UpdateWebSite(context.Context, *UpdateWebSiteRequest) (*UpdateWebSiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWebSite not implemented")
}
func (*UnimplementedWebSiteServiceServer) DeleteWebSite(context.Context, *DeleteWebSiteRequest) (*DeleteWebSiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWebSite not implemented")
}
func (*UnimplementedWebSiteServiceServer) ListWebSites(context.Context, *ListWebSiteRequest) (*ListWebSiteResults, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWebSites not implemented")
}

func RegisterWebSiteServiceServer(s *grpc.Server, srv WebSiteServiceServer) {
	s.RegisterService(&_WebSiteService_serviceDesc, srv)
}

func _WebSiteService_CreateWebSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSiteServiceServer).CreateWebSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebSiteService/CreateWebSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSiteServiceServer).CreateWebSite(ctx, req.(*CreateWebSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebSiteService_ReadWebSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadWebSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSiteServiceServer).ReadWebSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebSiteService/ReadWebSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSiteServiceServer).ReadWebSite(ctx, req.(*ReadWebSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebSiteService_UpdateWebSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWebSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSiteServiceServer).UpdateWebSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebSiteService/UpdateWebSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSiteServiceServer).UpdateWebSite(ctx, req.(*UpdateWebSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebSiteService_DeleteWebSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSiteServiceServer).DeleteWebSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebSiteService/DeleteWebSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSiteServiceServer).DeleteWebSite(ctx, req.(*DeleteWebSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebSiteService_ListWebSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSiteServiceServer).ListWebSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v0.WebSiteService/ListWebSites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSiteServiceServer).ListWebSites(ctx, req.(*ListWebSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebSiteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v0.WebSiteService",
	HandlerType: (*WebSiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWebSite",
			Handler:    _WebSiteService_CreateWebSite_Handler,
		},
		{
			MethodName: "ReadWebSite",
			Handler:    _WebSiteService_ReadWebSite_Handler,
		},
		{
			MethodName: "UpdateWebSite",
			Handler:    _WebSiteService_UpdateWebSite_Handler,
		},
		{
			MethodName: "DeleteWebSite",
			Handler:    _WebSiteService_DeleteWebSite_Handler,
		},
		{
			MethodName: "ListWebSites",
			Handler:    _WebSiteService_ListWebSites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web_site.proto",
}
