---
version: "3.8"

services:

  arangodb:
    image: "quaerereplatform/quaerere-arangodb:latest"
    ports:
      - "8529:8529"
    env_file:
      - ".env.arangodb"

  columbia:
    build:
      context: .
      dockerfile: ./build/docker/dev/Dockerfile
    working_dir: /webapp
    environment:
      air_wd: /webapp
    ports:
      - 8081:1323
    volumes:
      - ./:/webapp
    command: ["-c", "./build/docker/dev/columbia/air.conf"]

  kootenay:
    build:
      context: .
      dockerfile: ./build/docker/dev/Dockerfile
    depends_on:
      - arangodb
    working_dir: /webapp
    environment:
      air_wd: /webapp
    ports:
      - 8080:1323
    volumes:
      - ./:/webapp
    command: ["-c", "./build/docker/dev/kootenay/air.conf"]
