---
version: "3.7"

services:

  columbia:
    build:
      context: .
      dockerfile: ./build/docker/dev/Dockerfile
    working_dir: /webapp
    environment:
      air_wd: /webapp
    ports:
      - 8080:1323
    volumes:
      - ./:/webapp
    command: ["-c", "./build/docker/dev/columbia/air.conf"]

  kootenay:
    build:
      context: .
      dockerfile: ./build/docker/dev/Dockerfile
    working_dir: /webapp
    environment:
      air_wd: /webapp
    ports:
      - 8081:1323
    volumes:
      - ./:/webapp
    command: ["-c", "./build/docker/dev/kootenay/air.conf"]
