
storage_backend = "arangodb"

[datastore.arangodb]
auth_type = "basic"
database = "quaerere"
endpoints = ["http://localhost:8529/"]
password = "password"
username = "quaerere"

[serve.http]
bind = "0.0.0.0"
port = 1323
tls_disabled = true

[serve.grpc]
bind = "0.0.0.0"
port = 9090
